### PR TITLE
Scroll on new lines

### PR DESCRIPTION
**Pull request by DaniGuardiola**
This addition will make sure that the document scrolls properly when inserting a new line. You might want to make it optional and have a setting for it. I am using this by modifying the installed extension code directly, and it works like a charm, but it's not tested properly as I haven't tried compiling the ts files.

### CODE REVIEW

**Comment by mauricedb** [comment]
Sweet, I like it :-)

Thanks for the PR

**Comment by DaniGuardiola** [comment]
Thanks! Although I just thought of a case where it would break. If you're not on the last line (for example after a go-to) then newlines will make it scroll to the end. Should probably reveal the current line (the one where the cursor is after inserting the new line) instead of the last line.

**Comment by mauricedb** [comment]
Hi @DaniGuardiola 

This change should fix that issue #12

**Comment by DaniGuardiola** [comment]
Great! Thanks

**Pull request merged**
